spring.application.name=ms-geolocalizacion

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sanosysalvos_geolocalizacion?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8084

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI:https://sts.windows.net/14cc35b0-80bc-4ffd-b90a-1fc02097a113/}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${ENTRA_JWK_SET_URI:https://login.microsoftonline.com/14cc35b0-80bc-4ffd-b90a-1fc02097a113/discovery/keys}
entra.security.audience=${ENTRA_AUDIENCE:api://d88e02e7-1a2d-4d8c-b8f8-ad917d8adeac}
