spring.application.name=gateway-sanosysalvos

server.port=8080

spring.cloud.gateway.routes[0].id=usuarios-route
spring.cloud.gateway.routes[0].uri=${MS_USUARIOS_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/bff/usuarios,/bff/usuarios/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/bff/usuarios(?<segment>/?.*),/api/usuarios${segment}

spring.cloud.gateway.routes[1].id=mascotas-route
spring.cloud.gateway.routes[1].uri=${MS_MASCOTAS_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/bff/mascotas,/bff/mascotas/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/bff/mascotas(?<segment>/?.*),/api/mascotas${segment}

spring.cloud.gateway.routes[2].id=coincidencias-route
spring.cloud.gateway.routes[2].uri=${MS_COINCIDENCIAS_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/bff/coincidencias,/bff/coincidencias/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/bff/coincidencias(?<segment>/?.*),/api/coincidencias${segment}

spring.cloud.gateway.routes[3].id=geolocalizacion-route
spring.cloud.gateway.routes[3].uri=${MS_GEOLOCALIZACION_URL:http://localhost:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/bff/geolocalizacion,/bff/geolocalizacion/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/bff/geolocalizacion(?<segment>/?.*),/api/geolocalizacion${segment}

