spring.application.name=bff-sanosysalvos

server.port=8080

ms.mascotas.url=${MS_MASCOTAS_URL:http://localhost:8082}
ms.usuarios.url=${MS_USUARIOS_URL:http://localhost:8081}
ms.coincidencias.url=${MS_COINCIDENCIAS_URL:http://localhost:8083}