spring.application.name=ms-coincidencias

server.port=8083

ms.mascotas.url=${MS_MASCOTAS_URL:http://localhost:8082}
ms.geolocalizacion.url=${MS_GEOLOCALIZACION_URL:http://localhost:8084}
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.waitDurationInOpenState=10s
