spring.application.name=ms-coincidencias

server.port=8083

ms.mascotas.url=${MS_MASCOTAS_URL:http://localhost:8082}
ms.geolocalizacion.url=${MS_GEOLOCALIZACION_URL:http://localhost:8084}
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.geolocalizacionCircuitBreaker.waitDurationInOpenState=10s

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI:https://sts.windows.net/14cc35b0-80bc-4ffd-b90a-1fc02097a113/}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${ENTRA_JWK_SET_URI:https://login.microsoftonline.com/14cc35b0-80bc-4ffd-b90a-1fc02097a113/discovery/keys}
entra.security.audience=${ENTRA_AUDIENCE:api://d88e02e7-1a2d-4d8c-b8f8-ad917d8adeac}
